# Generated by Django 5.0.6 on 2024-10-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_aliment', models.CharField(max_length=50)),
                ('quantite', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name_animal', models.CharField(max_length=50)),
                ('description', models.TextField(default=' ')),
                ('poids', models.IntegerField(default=' ')),
                ('naissance', models.BooleanField(default=False)),
                ('vente', models.BooleanField(default=False)),
                ('deces', models.BooleanField(default=False)),
                ('achat', models.BooleanField(default=False)),
                ('sexe', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2)),
                ('date_enregistrer', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_animal', models.BooleanField(default=False)),
                ('motif', models.CharField(max_length=50)),
                ('date_fin', models.DateTimeField()),
                ('animal', models.ManyToManyField(to='animaleapp.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaleapp.aliment', verbose_name='aliment')),
            ],
        ),
        migrations.CreateModel(
            name='Histoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entre', models.IntegerField(default=0)),
                ('sortie', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('aliment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaleapp.aliment')),
                ('nourrir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaleapp.nourriture')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50, unique=True)),
                ('quantite', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('aliment', models.ManyToManyField(to='animaleapp.aliment')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animaleapp.classe')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matin', models.BooleanField(default=False)),
                ('midi', models.BooleanField(default=False)),
                ('soir', models.BooleanField(default=False)),
                ('do_type', models.BooleanField(default=False)),
                ('do_matin', models.BooleanField(default=False)),
                ('do_midi', models.BooleanField(default=False)),
                ('do_soir', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('typee', models.ManyToManyField(to='animaleapp.typeanimal')),
            ],
        ),
        migrations.AddField(
            model_name='nourriture',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaleapp.typeanimal', verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deces', models.IntegerField(default=0)),
                ('naissance', models.IntegerField(default=0)),
                ('achat', models.IntegerField(default=0)),
                ('vente', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaleapp.animal')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaleapp.typeanimal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='typee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animaleapp.typeanimal'),
        ),
    ]
