# Generated by Django 5.0.6 on 2024-10-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_enregistrer',
            field=models.DateTimeField(null=True),
        ),
    ]
