# Generated by Django 5.0.6 on 2024-10-20 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_champ', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_culture', models.CharField(max_length=50)),
                ('date_plante', models.DateTimeField()),
                ('date_recolte', models.DateTimeField()),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultureapp.champ')),
            ],
        ),
        migrations.CreateModel(
            name='Arroser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matin_culture', models.BooleanField(default=False)),
                ('midi_culture', models.BooleanField(default=False)),
                ('soir_culture', models.BooleanField(default=False)),
                ('date_arroser', models.DateTimeField()),
                ('do_culture', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultureapp.champ')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultureapp.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_sorti', models.IntegerField(default=0)),
                ('date_sorti', models.DateTimeField(auto_now=True)),
                ('quantite_entre', models.IntegerField(default=0)),
                ('tolal', models.IntegerField(default=0)),
                ('date_entre', models.DateTimeField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultureapp.culture')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_produit', models.IntegerField(default=0)),
                ('entre', models.BooleanField(default=0)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultureapp.culture')),
            ],
        ),
    ]
